update github actions

diff --git a/.github/workflows/ckan-latest.yml b/.github/workflows/ckan-latest.yml
--- a/.github/workflows/ckan-latest.yml
+++ b/.github/workflows/ckan-latest.yml
@@ -22,11 +22,11 @@ jobs:
         run: node index
 
       - name: Commit and Push CSV
-        run:
+        run: |
           git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
           git config --global user.name "github-actions[bot]"
-          git add -f path/to/your/data.csv
-          git commit -m "Update CSV file" || true
+          git add -f data/ckan-updates.csv
+          git commit -m "Update CSV file" || true  # The script won't fail if there's nothing to commit
           git push
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
